name: Java CI

on: [push]

jobs:
  test:
    name: Test on jdk ${{ matrix.jdk_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk_version: [1.8, 1.11, 1.12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use JDK ${{ matrix.jdk_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk_version }}

      - name: Build and Test, verify with Maven
        run: |
          mvn package --file pom.xml
          mvn test
          mvn verify
